# Generated by Django 2.1.4 on 2019-01-03 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trains', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название маршрута')),
                ('from_city', models.CharField(max_length=100, verbose_name='Откуда')),
                ('to_city', models.CharField(max_length=100, verbose_name='Куда')),
                ('travel_times', models.IntegerField(verbose_name='Время в пути')),
                ('across_cities', models.ManyToManyField(blank=True, to='trains.Train', verbose_name='Через города')),
            ],
            options={
                'verbose_name_plural': 'Маршруты',
                'verbose_name': 'Маршрут',
                'ordering': ['name'],
            },
        ),
    ]
